bundler_args:
  --without development debug darwin

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
  - "nohup bundle exec thin start -R spec/integration/sinatra.ru -p 8888 &"
  - "sleep 2"

env:
 - SERVER=http://localhost:8888

language: ruby

script: "bundle exec rake spec:integration && bundle exec rake spec"

rvm:
  - 1.9.2
  - 1.9.3